modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "nationcurrency"
version = "1.0.0"
displayName = "Nation Currency"
authors = "Developer"
description = '''
Un mod de economía para servidores multijugador con múltiples naciones.
Permite crear billetes únicos con códigos personalizados usando una máquina impresora 3x3.
'''

[[dependencies.nationcurrency]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.165,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nationcurrency]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"
